<?php
$addons = array(
	"access8math" => "https://github.com/tsengwoody/Access8Math/releases/download/v3.2/Access8Math-3.2.nvda-addon",
	"addonshelp" => "https://github.com/ruifontes/addonsHelp/releases/download/2022.03/addonsHelp-2022.03.nvda-addon",
	"appdict" => "https://github.com/ruifontes/applicationDictionary-/releases/download/2022.03.26/applicationDictionary-2022.03.26.nvda-addon",
	"ath" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"ath-dev" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"audiochart" => "https://github.com/mltony/nvda-audio-chart/releases/download/v1.3/audioChart-1.3.nvda-addon",
	"bc" => "bitChe-2.8.nvda-addon",
	"bc-dev" => "bitChe-2.8.nvda-addon",
	"beepkeyboard" => "https://github.com/davidacm/beepKeyboard/releases/download/1.7/beepKeyboard-1.7.nvda-addon",
	"bgt" => "https://github.com/sykesman/NVDA-BGT/releases/download/1.0-dev/bgt_lullaby-1.0-dev.nvda-addon",
	"brlext" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest",
	"brlext-dev" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest?channel=dev",
	"browsernav" => "https://github.com/mltony/nvda-browser-nav/releases/download/v1.15.1/browsernav-1.15.nvda-addon",
	"btaudio" => "https://github.com/mltony/nvda-bluetooth-audio/releases/download/v1.4/bluetoothaudio-1.4.nvda-addon",
	"cac" => "https://github.com/hkatic/clock/releases/download/v22.01/clock-22.01.nvda-addon",
	"cac-dev" => "https://github.com/hkatic/clock/releases/download/v22.01/clock-22.01.nvda-addon",
	"cae" => "https://github.com/javidominguez/Calibre/releases/download/2.6/calibre-2.6.nvda-addon",
	"cae-dev" => "https://github.com/javidominguez/Calibre/releases/download/dev220326/calibre-dev220326.nvda-addon",
	"chari" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.8/charInfo-1.8.nvda-addon",
	"chari-dev" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.8/charInfo-1.8.nvda-addon",
	"clsel" => "https://github.com/tspivey/classicSelection/releases/download/v1.2/classicSelection-1.2.nvda-addon",
	"ccd" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/15.0/clipContentsDesigner-15.0.nvda-addon",
	"ccd-dev" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/16.0-dev/clipContentsDesigner-16.0-dev.nvda-addon",
	"ccd-o" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/7.2/clipContentsDesigner-7.2.nvda-addon",
	"cig" => "https://github.com/grisov/checkGestures/releases/download/latest/checkGestures-1.0.2.nvda-addon",
	"ckbl" => "https://github.com/abdel792/sayCurrentKeyboardLanguage/releases/download/v21.11/sayCurrentKeyboardLanguage-21.11.nvda-addon",
	"ckbl-dev" => "https://github.com/abdel792/sayCurrentKeyboardLanguage/releases/download/v21.11-dev/sayCurrentKeyboardLanguage-21.11-dev.nvda-addon",
	"cr" => "https://github.com/ABuffEr/columnsReview/releases/download/v4.0/columnsReview-4.0.nvda-addon",
	"cr-dev" => "https://github.com/ABuffEr/columnsReview/releases/download/b20220330/columnsReview-20220330-dev.nvda-addon",
	"crh-dev" => "https://files.derekriemer.com/crashHero-dev.nvda-addon",
	"cs" => "https://github.com/ruifontes/clipspeak/releases/download/2022.04/clipspeak-2022.04.nvda-addon",
	"cont" => "https://github.com/derekriemer/consoleTimer/releases/download/v1.0/consoleTimer-1.0.nvda-addon",
	"consoletoolkit" => "https://github.com/mltony/nvda-console-toolkit/releases/download/v1.2/consoleToolkit-1.2.nvda-addon",
	"cua" => "https://github.com/josephsl/controlUsageAssistant/releases/download/22.01/controlUsageAssistant-22.01.nvda-addon",
	"cua-dev" => "https://github.com/nvdaes/controlUsageAssistant/releases/download/2022.04.11-dev/controlUsageAssistant-2022.04.11-dev.nvda-addon",
	"debughelper" => "https://github.com/XLTechie/devHelper/releases/download/v1.4/devHelper-1.4.nvda-addon",
	"devtoolkit" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/20.06/developerToolkit-20.06.nvda-addon",
	"devtoolkit-dev" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/20.06/developerToolkit-20.06.nvda-addon",
	"directlink" => "https://github.com/fawazar94/DirectLink/releases/download/1.0/directLink-1.0.nvda-addon",
	"dw" => "https://github.com/abdel792/dayOfTheWeek/releases/download/v21.11/dayOfTheWeek-21.11.nvda-addon",
	"dw-dev" => "https://github.com/abdel792/dayOfTheWeek/releases/download/v21.11-dev/dayOfTheWeek-21.11-dev.nvda-addon",
	"dx" => "https://github.com/Nardol/dropbox/releases/download/4.7/dropbox-4.7.nvda-addon",
	"dx-dev" => "https://github.com/Nardol/dropbox/releases/download/4.7/dropbox-4.7.nvda-addon",
	"earia" => "https://github.com/jmdaweb/enhancedAria/releases/download/v2.8/enhancedAria-2.8.nvda-addon",
	"em" => "https://github.com/nvdaes/emule/releases/download/5.0/eMule-5.0.nvda-addon",
	"em-dev" => "https://github.com/nvdaes/emule/releases/download/6.0-dev/eMule-6.0-dev.nvda-addon",
	"emo" => "https://github.com/nvdaes/emoticons/releases/download/14.7/emoticons-14.7.nvda-addon",
	"emo-dev" => "https://github.com/nvdaes/emoticons/releases/download/15.0-dev/emoticons-15.0-dev.nvda-addon",
	"emo-o" => "https://github.com/nvdaes/emoticons/releases/download/6.5/emoticons-6.5.nvda-addon",
	"epr" => "https://github.com/davidacm/EnhancedPhoneticReading/releases/download/1.0/EnhancedPhoneticReading-1.0.nvda-addon",
	"epr-dev" => "https://github.com/davidacm/EnhancedPhoneticReading/releases/download/1.1.1-dev/EnhancedPhoneticReading-1.1.1-dev.nvda-addon",
	"etn" => "https://github.com/Oreonan/easyTableNavigator-1/releases/download/2.2.1/easyTableNavigator-2.2.1.nvda-addon",
	"etn-dev" => "https://github.com/Oreonan/easyTableNavigator-1/releases/download/v2.2.1-dev/easyTableNavigator-v2.2.1-dev.nvda-addon",
	"ets" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/22.03/enhancedTouchGestures-22.03.1.nvda-addon",
	"evttracker" => "https://github.com/josephsl/evtTracker/releases/download/21.10/evtTracker-21.10.nvda-addon",
	"ew" => "https://github.com/josephsl/extendedWinamp/releases/download/2.1/extendedWinamp-2.1.nvda-addon",
	"fh" => "https://github.com/nvdajp/focusHighlight/releases/download/6.4/focusHighlight-6.4.nvda-addon",
	"fh-dev" => "https://github.com/nvdajp/focusHighlight/releases/download/6.4/focusHighlight-6.4.nvda-addon",
	"gc" => "https://github.com/josephsl/goldenCursor/releases/download/5.1/goldenCursor-5.1.nvda-addon",
	"gc-dev" => "https://github.com/josephsl/goldenCursor/releases/download/5.1/goldenCursor-5.1.nvda-addon",
	"gl" => "https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/guideLines",
	"gwv" => "https://github.com/josephsl/goldWave/releases/download/22.03/goldwave-22.03.1.nvda-addon",
	"ibir" => "https://github.com/SamKacer/IgnoreBlanksIndentation/releases/download/v0.3/ignoreBlanksIndentationReporting-0.3.nvda-addon",
	"imgdesc" => "https://storage.googleapis.com/www.screenreader.ai/addons/ImageDescriber-1.2.1.nvda-addon",
	"it" => "https://github.com/beqabeqa473/instantTranslate/releases/download/v4.4.2/instantTranslate-4.4.2.nvda-addon",
	"it-dev" => "https://github.com/beqabeqa473/instantTranslate/releases/download/v4.4.2/instantTranslate-4.4.2.nvda-addon",
	"indentnav" => "https://github.com/mltony/nvda-indent-nav/releases/download/v1.13/IndentNav-1.13.nvda-addon",
	"inputlock" => "https://github.com/jmdaweb/inputLock/releases/download/v1.10/inputLock-1.10.nvda-addon",
	"killnvda" => "https://github.com/tspivey/killNVDA/releases/download/v0.2/killNVDA-0.2.nvda-addon",
	"lambda" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"lambda-dev" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"mp3dc" => "https://github.com/abdel792/mp3DirectCut/releases/download/v21.11/mp3DirectCut-21.11.nvda-addon",
	"mp3dc-dev" => "https://github.com/abdel792/mp3DirectCut/releases/download/v21.11-dev/mp3DirectCut-21.11-dev.nvda-addon",
	"mirc" => "mirc-1.6.nvda-addon",
	"moz" => "https://github.com/javidominguez/MozillaScripts/releases/download/1.16/Mozilla-1.16.nvda-addon",
	"msedge" => "https://github.com/beqabeqa473/MSEdgeDiscardAnnouncements/releases/download/v0.5/MSEdgeDiscardAnnouncements-0.5.nvda-addon",
	"mush" => "mushClient-1.3.nvda-addon",
	"nb" => "https://github.com/ABuffEr/noBeepsSpeechMode/releases/download/v5.1/noBeepsSpeechMode-5.1.nvda-addon",
	"nb-old" => "https://github.com/ABuffEr/noBeepsSpeechMode/releases/download/v4.0/noBeepsSpeechMode-4.0.nvda-addon",
	"NotepadPlusPlus" => "https://files.derekriemer.com/NotepadPlusPlus-2019.09.0.nvda-addon",
	"numpadNav" => "https://github.com/opensourcesys/numpadNavMode/releases/download/1.5/numpadNavMode-1.5.nvda-addon",
	"nvda3208" => "https://github.com/josephsl/addonUpdater/releases/download/22.03/addonUpdater-22.03.1.nvda-addon",
	"nvda7857" => "screenCurtain-20191130.nvda-addon",
	"nvdaproxy" => "https://github.com/nvda-es/nvda-proxy-support/releases/download/v1.0.3/proxy-1.0.3.nvda-addon",
	"nvdaremote" => "https://nvdaremote.com/remote-2.5.nvda-addon",
	"nvsp" => "https://www.nvaccess.org/files/nvda-addons/nvSpeechPlayer_2020.1.nvda-addon",
	"objLoc" => "https://github.com/josephsl/objLocationTones/releases/download/20.12/objLocTones-20.12.nvda-addon",
	"objPad" => "https://github.com/josephsl/objPad/releases/download/21.06/objPad-21.06.nvda-addon",
	"ocr" => "https://github.com/lukaszgo1/nvda-ocr/releases/download/v2.2/ocr-2.2.nvda-addon",
	"oid-dev" => "https://github.com/larry801/online_ocr/releases/download/0.17-dev/onlineOCR-0.17-dev.nvda-addon",
	"outlookextended" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.8/outlookExtended-1.8.nvda-addon",
	"outlookextended-dev" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.9-dev-20211020/outlookExtended-1.9-dev-20211020.nvda-addon",
	"pckbbrl" => "https://github.com/nvdaes/pcKbBrl/releases/download/2022.03.26/pcKbBrl-2022.03.26.nvda-addon",
	"pckbbrl-dev" => "https://github.com/nvdaes/pcKbBrl/releases/download/2022.03.26/pcKbBrl-2022.03.26.nvda-addon",
	"pckbbrl-o" => "https://www.nvaccess.org/files/nvda-addons/pcKbBrl-2014.1.nvda-addon",
	"perChk" => "https://github.com/lukaszgo1/percentageChecker/releases/download/v1.3-dev/percentageChecker-1.3-dev.nvda-addon",
	"pm" => "https://github.com/nvdaes/placeMarkers/releases/download/19.0.1/placeMarkers-19.0.1.nvda-addon",
	"pm-dev" => "https://github.com/nvdaes/placeMarkers/releases/download/20.0-dev/placeMarkers-20.0-dev.nvda-addon",
	"pm-o" => "https://github.com/nvdaes/placeMarkers/releases/download/10.2/placeMarkers-10.2.nvda-addon",
	"phoneticpunc" => "https://github.com/mltony/nvda-phonetic-punctuation/releases/download/v1.6/phoneticPunctuation-1.6.nvda-addon",
	"qb-dev" => "https://www.nvaccess.org/files/nvda-addons/quickBooks2014-2014.4.7.nvda-addon",
	"quickdictionary" => "https://github.com/grisov/quickDictionary/releases/download/latest/quickDictionary-2.1.4.nvda-addon",
	"quickNotetaker" => "https://github.com/mohammad-suliman/quickNotetaker/releases/download/v1.0/quickNotetaker-1.0.nvda-addon",
	"rccp" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.3/reviewCursorCopier-1.3.nvda-addon",
	"rccp-dev" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.3/reviewCursorCopier-1.3.nvda-addon",
	"rf" => "https://github.com/nvdaes/readFeeds/releases/download/13.0/readFeeds-13.0.nvda-addon",
	"rf-dev" => "https://github.com/nvdaes/readFeeds/releases/download/13.0/readFeeds-13.0.nvda-addon",
	"rf-o" => "https://github.com/nvdaes/readFeeds/releases/download/4.5/readFeeds-4.5.nvda-addon",
	"rm" => "https://github.com/josephsl/resourceMonitor/releases/download/22.03/resourceMonitor-22.03.1.nvda-addon",
	"rp" => "https://github.com/nvdaes/reportPasswords/releases/download/3.0/reportPasswords-3.0.nvda-addon",
	"rp-dev" => "https://github.com/nvdaes/reportPasswords/releases/download/3.0/reportPasswords-3.0.nvda-addon",
	"rsy" => "https://github.com/nvdaes/reportSymbols/releases/download/7.0/reportSymbols-7.0.nvda-addon",
	"rsy-dev" => "https://github.com/nvdaes/reportSymbols/releases/download/7.0/reportSymbols-7.0.nvda-addon",
	"rsy-o" => "https://github.com/nvdaes/reportSymbols/releases/download/3.6/reportSymbols-3.6.nvda-addon",
	"scrsw" => "https://github.com/javidominguez/screenshots/releases/download/1.0/screenshots-1.0.nvda-addon",
	"searchwith" => "https://github.com/ibrahim-s/searchWith/releases/download/v2.0/searchWith-2.0.nvda-addon",
	"sentencenav" => "https://github.com/mltony/nvda-sentence-nav/releases/download/v2.12/SentenceNav-2.12.nvda-addon",
	"soundsplitter" => "https://github.com/josephsl/soundSplitter/releases/download/22.03/soundSplitter-22.03.1.nvda-addon",
	"speechlogger" => "https://github.com/opensourcesys/speechLogger/releases/download/22.1.0/speechLogger-22.1.0.nvda-addon",
	"spie" => "https://www.nvaccess.org/files/nvda-addons/speechPlayerInEspeak-0.4.nvda-addon",
	"spl" => "https://github.com/josephsl/stationPlaylist/releases/download/22.03/stationPlaylist-22.03.1.nvda-addon",
	"spnav" => "https://github.com/Nardol/SayProductNameAndVersion/releases/download/2022.04/sayProductNameAndVersion-2022.04.nvda-addon",
	"sps" => "https://github.com/jscholes/nvda-speech-history/releases/download/2021.1/speechHistory-2021.1.nvda-addon",
	"st" => "https://github.com/ruifontes/systrayList/releases/download/2022.03/systrayList-2022.03.nvda-addon",
	"sws" => "https://github.com/tspivey/switchSynth/releases/download/v1.04/switchSynth-1.04.nvda-addon",
	"spp" => "https://github.com/tspivey/speakPasswords/releases/download/v1.01/speakPasswords-1.01.nvda-addon",
	"synthrings" => "https://github.com/davidacm/synthRingSettingsSelector/releases/download/1.0/synthRingSettingsSelector-1.0.nvda-addon",
	"tbx" => "https://github.com/ABuffEr/toolbarsExplorer/releases/download/v1.6/toolbarsExplorer-1.6.nvda-addon",
	"tbx-dev" => "https://github.com/ABuffEr/toolbarsExplorer/releases/download/20220409-dev/toolbarsExplorer-20220409-dev.nvda-addon",
	"textnav" => "https://github.com/mltony/nvda-text-nav/releases/download/v1.6/textnav-1.6.nvda-addon",
	"tmast" => "https://github.com/nvdaaddons/toneMaster/releases/download/v1.3/toneMaster-1.3.nvda-addon",
	"tod-dev" => "https://files.derekriemer.com/tipOfTheDay-dev.nvda-addon",
	"tod" => "https://files.derekriemer.com/tipOfTheDay.nvda-addon",
	"tony" => "https://github.com/mltony/nvda-tonys-enhancements/releases/download/v1.13/tonysEnhancements-1.13.nvda-addon",
	"trainingkbdcmd" => "https://github.com/ibrahim-s/trainingNvdaCommands/releases/download/2.6/trainingKeyboardCommands-2.6.nvda-addon",
	"tv" => "teamViewer-2.3.nvda-addon",
	"tv-dev" => "teamViewer-3.0-dev.nvda-addon",
	"txtinfo" => "https://github.com/cartertemm/text_information/releases/download/v1.1/textInformation-1.1.nvda-addon",
	"tz" => "https://github.com/munawarb/NVDA-Time-Zoner/releases/download/v3.01/timezone-3.01.nvda-addon",
	"ubi" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.2/unicodeBrailleInput-3.2.nvda-addon",
	"ubi-dev" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.2/unicodeBrailleInput-3.2.nvda-addon",
	"unmute" => "https://github.com/grisov/Unmute/releases/download/latest/unmute-1.5.5.nvda-addon",
	"updchannelselect" => "https://github.com/nvda-es/updateChannel/releases/download/v1.1/updateChannel-1.1.nvda-addon",
	"VR" => "https://github.com/ruifontes/virtualReview/releases/download/21.06/virtualRevision-21.06.nvda-addon",
	"vlc" => "https://github.com/javidominguez/VLC/releases/download/2.14/VLC-2.14.nvda-addon",
	"vlc-dev" => "https://github.com/javidominguez/VLC/releases/download/2.13/VLC-2.13.nvda-addon",
	"vent" => "Ventrilo-1.0-dev.nvda-addon",
	"w10" => "https://github.com/josephsl/wintenApps/releases/download/22.03/wintenApps-22.03.2.nvda-addon",
	"w10-dev" => "https://www.josephsl.net/files/nvdaaddons/getupdate.php?file=w10-dev",
	"wc" => "https://github.com/ruifontes/wordCount/releases/download/2022.03/wordCount-2022.03.nvda-addon",
	"wetp" => "https://www.nvda.it/files/plugin/weather_plus8.8.nvda-addon",
	"winmag" => "https://github.com/CyrilleB79/winMag/releases/download/V2.0/winMag-2.0.nvda-addon",
	"winmag-dev" => "https://github.com/CyrilleB79/winMag/releases/download/V2.0/winMag-2.0.nvda-addon",
	"winwizard" => "https://github.com/lukaszgo1/winWizard/releases/download/V5.0.3/winWizard-5.0.3.nvda-addon",
	"wordnav" => "https://github.com/mltony/nvda-word-nav/releases/download/v1.7/wordNav-1.7.nvda-addon",
	"zoom" => "zoomEnhancements-1.1.1.nvda-addon",
);

If (isset($_GET['file'])) {
	$file = $_GET['file'];
	$fullname = $addons[$file];

	if ($fullname != "") {
		Header('Location:'.$fullname);
	} else {
		header("HTTP/1.0 404 Not Found");
		print "<h1>File not found</h1>";
		print "<p>The file you requested could not be found on this server.</p>";
		print "<p>Please check that the link that brought you here is correct and try again.</p>";
		print "<p>Thanks</p>";
	}
} else If (isset($_GET['addonslist'])) {
	echo json_encode($addons);
} else {
	print "<h1>Error:</h1>";
	print "<p>Please check that the link that brought you here is correct and try again.</p>";
	print "<p>If you continue to see this message report this error to the nvda addon list.</p>";
	print "<p>Thanks</p>";
}
?>
