<?php
$addons = array(
	"access8math" => "https://github.com/tsengwoody/Access8Math/releases/download/v3.0/Access8Math-3.0.nvda-addon",
	"addonshelp" => "https://github.com/ruifontes/addonsHelp/releases/download/21.05/addonsHelp-21.05.nvda-addon",
	"ath" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"ath-dev" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"audiochart" => "https://github.com/mltony/nvda-audio-chart/releases/download/v1.3/audioChart-1.3.nvda-addon",
	"bc" => "bitChe-2.8.nvda-addon",
	"bc-dev" => "bitChe-2.8.nvda-addon",
	"beepkeyboard" => "beepKeyboard-1.3.nvda-addon",
	"bgt" => "https://github.com/sykesman/NVDA-BGT/releases/download/1.0-dev/bgt_lullaby-1.0-dev.nvda-addon",
	"brlext" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest",
	"brlext-dev" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest?channel=dev",
	"browsernav" => "https://github.com/mltony/nvda-browser-nav/releases/download/v1.15.1/browsernav-1.15.nvda-addon",
	"btaudio" => "https://github.com/mltony/nvda-bluetooth-audio/releases/download/v1.3/bluetoothaudio-1.3.nvda-addon",
	"cac" => "https://github.com/hkatic/clock/releases/download/v19.12/clock-19.12.nvda-addon",
	"cac-dev" => "https://github.com/hkatic/clock/releases/download/v20.12-dev/clock-20.12-dev.nvda-addon",
	"cae" => "https://github.com/javidominguez/Calibre/releases/download/2.4/calibre-2.4.nvda-addon",
	"cae-dev" => "https://github.com/javidominguez/Calibre/releases/download/dev210609/calibre-dev210609.nvda-addon",
	"chari" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.6/charInfo-1.6.nvda-addon",
	"chari-dev" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.6/charInfo-1.6.nvda-addon",
	"clsel" => "https://github.com/tspivey/classicSelection/releases/download/v1.1/classicSelection-1.1.nvda-addon",
	"ccd" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/14.0/clipContentsDesigner-14.0.nvda-addon",
	"ccd-dev" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/14.0/clipContentsDesigner-14.0.nvda-addon",
	"ccd-o" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/7.2/clipContentsDesigner-7.2.nvda-addon",
	"cig" => "https://github.com/grisov/checkGestures/releases/download/latest/checkGestures-1.0.2.nvda-addon",
	"ckbl" => "https://github.com/abdel792/sayCurrentKeyboardLanguage/releases/download/v19.12/sayCurrentKeyboardLanguage-19.12.nvda-addon",
	"ckbl-dev" => "https://github.com/abdel792/sayCurrentKeyboardLanguage/releases/download/v19.12/sayCurrentKeyboardLanguage-19.12.nvda-addon",
	"cr" => "columnsReview-3.0-20200511-dev.nvda-addon",
	"cr-dev" => "columnsReview-3.0-20200511-dev.nvda-addon",
	"crh-dev" => "https://files.derekriemer.com/crashHero-dev.nvda-addon",
	"cs" => "clipspeak-1.1.nvda-addon",
	"cont" => "https://github.com/derekriemer/consoleTimer/releases/download/v1.0/consoleTimer-1.0.nvda-addon",
	"consoletoolkit" => "https://github.com/mltony/nvda-console-toolkit/releases/download/v1.1/consoleToolkit-1.1.nvda-addon",
	"cua" => "https://github.com/josephsl/controlUsageAssistant/releases/download/21.06/controlUsageAssistant-21.06.nvda-addon",
	"cua-dev" => "https://github.com/josephsl/controlUsageAssistant/releases/download/21.06/controlUsageAssistant-21.06.nvda-addon",
	"debughelper" => "https://github.com/XLTechie/devHelper/releases/download/v1.4/devHelper-1.4.nvda-addon",
	"devtoolkit" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/20.04/developerToolkit-20.04.nvda-addon",
	"devtoolkit-dev" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/20.04/developerToolkit-20.04.nvda-addon",
	"directlink" => "https://github.com/fawazar94/DirectLink/releases/download/1.0/directLink-1.0.nvda-addon",
	"dw" => "https://github.com/abdel792/dayOfTheWeek/releases/download/v19.12/dayOfTheWeek-19.12.nvda-addon",
	"dw-dev" => "https://github.com/abdel792/dayOfTheWeek/releases/download/v19.12/dayOfTheWeek-19.12.nvda-addon",
	"dx" => "https://github.com/Nardol/dropbox/releases/download/v4.6/dropbox-4.6.nvda-addon",
	"dx-dev" => "https://github.com/Nardol/dropbox/releases/download/v4.6/dropbox-4.6.nvda-addon",
	"earia" => "https://github.com/jmdaweb/enhancedAria/releases/download/v2.8/enhancedAria-2.8.nvda-addon",
	"em" => "https://github.com/nvdaes/emule/releases/download/5.0/eMule-5.0.nvda-addon",
	"em-dev" => "https://github.com/nvdaes/emule/releases/download/5.0/eMule-5.0.nvda-addon",
	"emo" => "https://github.com/nvdaes/emoticons/releases/download/14.0/emoticons-14.0.nvda-addon",
	"emo-dev" => "https://github.com/nvdaes/emoticons/releases/download/14.0/emoticons-14.0.nvda-addon",
	"emo-o" => "https://github.com/nvdaes/emoticons/releases/download/6.5/emoticons-6.5.nvda-addon",
	"etn" => "easyTableNavigator-2.1.1.nvda-addon",
	"etn-dev" => "easyTableNavigator-2.1.1.nvda-addon",
	"ets" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/21.06/enhancedTouchGestures-21.06.nvda-addon",
	"ets-dev" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/21.06/enhancedTouchGestures-21.06.nvda-addon",
	"ew" => "https://github.com/josephsl/extendedWinamp/releases/download/2.0/extendedWinamp-2.0.nvda-addon",
	"fh" => "https://github.com/nvdajp/focusHighlight/releases/download/6.3/focusHighlight-6.3.nvda-addon",
	"fh-dev" => "https://github.com/nvdajp/focusHighlight/releases/download/6.2/focusHighlight-6.2.nvda-addon",
	"gc" => "goldenCursor-4.0.nvda-addon",
	"gc-dev" => "goldenCursor-4.0.nvda-addon",
	"gl" => "https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/guideLines",
	"gwv" => "https://github.com/josephsl/goldWave/releases/download/21.06/goldwave-21.06.nvda-addon",
	"imgdesc" => "https://storage.googleapis.com/www.screenreader.ai/addons/ImageDescriber-1.2.1.nvda-addon",
	"it" => "https://github.com/beqabeqa473/instantTranslate/releases/download/v4.4.2/instantTranslate-4.4.2.nvda-addon",
	"it-dev" => "https://github.com/beqabeqa473/instantTranslate/releases/download/v4.4.2/instantTranslate-4.4.2.nvda-addon",
	"indentnav" => "https://github.com/mltony/nvda-indent-nav/releases/download/v1.12/IndentNav-1.12.nvda-addon",
	"inputlock" => "https://github.com/jmdaweb/inputLock/releases/download/v1.9/inputLock-1.9.nvda-addon",
	"killnvda" => "https://github.com/tspivey/killNVDA/releases/download/v0.1/killNVDA-0.1.nvda-addon",
	"lambda" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"lambda-dev" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"mp3dc" => "https://github.com/abdel792/mp3DirectCut/releases/download/v20.12/mp3DirectCut-20.12.nvda-addon",
	"mp3dc-dev" => "https://github.com/abdel792/mp3DirectCut/releases/download/v20.11-dev/mp3DirectCut-20.11-dev.nvda-addon",
	"mirc" => "mirc-1.6.nvda-addon",
	"moz" => "https://github.com/javidominguez/MozillaScripts/releases/download/1.14/Mozilla-1.14.nvda-addon",
	"mush" => "mushClient-1.3.nvda-addon",
	"nb" => "noBeepsSpeechMode-2.5.nvda-addon",
	"NotepadPlusPlus" => "https://files.derekriemer.com/NotepadPlusPlus-2019.09.0.nvda-addon",
	"numpadNav" => "https://github.com/opensourcesys/numpadNavMode/releases/download/1.4/numpadNavMode-1.4.nvda-addon",
	"nvda3208" => "https://github.com/josephsl/addonUpdater/releases/download/21.07/addonUpdater-21.07.nvda-addon",
	"nvda7857" => "screenCurtain-20191130.nvda-addon",
	"nvdaproxy" => "https://github.com/nvda-es/nvda-proxy-support/releases/download/v1.0.3/proxy-1.0.3.nvda-addon",
	"nvdaremote" => "https://nvdaremote.com/remote-2.4.nvda-addon",
	"nvsp" => "https://www.nvaccess.org/files/nvda-addons/nvSpeechPlayer_2020.1.nvda-addon",
	"objLoc" => "https://github.com/josephsl/objLocationTones/releases/download/20.12/objLocTones-20.12.nvda-addon",
	"objPad" => "https://github.com/josephsl/objPad/releases/download/21.06/objPad-21.06.nvda-addon",
	"ocr" => "https://github.com/lukaszgo1/nvda-ocr/releases/download/v2.1/ocr-2.1.nvda-addon",
	"oid-dev" => "https://github.com/larry801/online_ocr/releases/download/0.17-dev/onlineOCR-0.17-dev.nvda-addon",
	"outlookextended" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.7/outlookExtended-1.7.nvda-addon",
	"outlookextended-dev" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.7/outlookExtended-1.7.nvda-addon",
	"pckbbrl" => "https://github.com/nvdaes/pcKbBrl/releases/download/2021.1/pcKbBrl-2021.1.nvda-addon",
	"pckbbrl-dev" => "https://github.com/nvdaes/pcKbBrl/releases/download/2021.1/pcKbBrl-2021.1.nvda-addon",
	"pckbbrl-o" => "https://www.nvaccess.org/files/nvda-addons/pcKbBrl-2014.1.nvda-addon",
	"perChk" => "https://github.com/lukaszgo1/percentageChecker/releases/download/v1.3-dev/percentageChecker-1.3-dev.nvda-addon",
	"pm" => "https://github.com/nvdaes/placeMarkers/releases/download/16.0/placeMarkers-16.0.nvda-addon",
	"pm-dev" => "https://github.com/nvdaes/placeMarkers/releases/download/16.0/placeMarkers-16.0.nvda-addon",
	"pm-o" => "https://github.com/nvdaes/placeMarkers/releases/download/10.2/placeMarkers-10.2.nvda-addon",
	"phoneticpunc" => "https://github.com/mltony/nvda-phonetic-punctuation/releases/download/v1.3/phoneticPunctuation-1.3.nvda-addon",
	"qb-dev" => "https://www.nvaccess.org/files/nvda-addons/quickBooks2014-2014.4.7.nvda-addon",
	"quickdictionary" => "https://github.com/grisov/quickDictionary/releases/download/latest/quickDictionary-2.1.4.nvda-addon",
	"rccp" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.3/reviewCursorCopier-1.3.nvda-addon",
	"rccp-dev" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.3/reviewCursorCopier-1.3.nvda-addon",
	"rf" => "https://github.com/nvdaes/readFeeds/releases/download/11.0/readFeeds-11.0.nvda-addon",
	"rf-dev" => "https://github.com/nvdaes/readFeeds/releases/download/11.0/readFeeds-11.0.nvda-addon",
	"rf-o" => "https://github.com/nvdaes/readFeeds/releases/download/4.5/readFeeds-4.5.nvda-addon",
	"rm" => "https://github.com/josephsl/resourceMonitor/releases/download/21.06/resourceMonitor-21.06.nvda-addon",
	"rm-dev" => "https://github.com/josephsl/resourceMonitor/releases/download/21.06/resourceMonitor-21.06.nvda-addon",
	"rp" => "https://github.com/nvdaes/reportPasswords/releases/download/2.0/reportPasswords-2.0.nvda-addon",
	"rp-dev" => "https://github.com/nvdaes/reportPasswords/releases/download/2.0/reportPasswords-2.0.nvda-addon",
	"rsy" => "https://github.com/nvdaes/reportSymbols/releases/download/6.0/reportSymbols-6.0.nvda-addon",
	"rsy-dev" => "https://github.com/nvdaes/reportSymbols/releases/download/6.0/reportSymbols-6.0.nvda-addon",
	"rsy-o" => "https://github.com/nvdaes/reportSymbols/releases/download/3.6/reportSymbols-3.6.nvda-addon",
	"sentencenav" => "https://github.com/mltony/nvda-sentence-nav/releases/download/v2.11/SentenceNav-2.11.nvda-addon",
	"spie" => "https://www.nvaccess.org/files/nvda-addons/speechPlayerInEspeak-0.4.nvda-addon",
	"spl" => "https://github.com/josephsl/stationPlaylist/releases/download/21.06/stationPlaylist-21.06.nvda-addon",
	"spl-dev" => "https://github.com/josephsl/stationPlaylist/releases/download/21.06/stationPlaylist-21.06.nvda-addon",
	"sps" => "https://github.com/jscholes/nvda-speech-history/releases/download/2020.2/speechHistory-2020.2.nvda-addon",
	"st" => "https://github.com/ruifontes/systrayList/releases/download/21.06/systrayList-21.06.nvda-addon",
	"sws" => "https://github.com/tspivey/switchSynth/releases/download/v1.03/switchSynth-1.03.nvda-addon",
	"spp" => "https://github.com/tspivey/speakPasswords/releases/download/v1.01/speakPasswords-1.01.nvda-addon",
	"synthrings" => "synthRingSettingsSelector-0.6.nvda-addon",
	"tbx" => "toolbarsExplorer-1.4.nvda-addon",
	"tbx-dev" => "toolbarsExplorer-1.4-20190825-dev.nvda-addon",
	"textnav" => "https://github.com/mltony/nvda-text-nav/releases/download/v1.5/textnav-1.5.nvda-addon",
	"tmast" => "https://github.com/nvdaaddons/toneMaster/releases/download/v1.3/toneMaster-1.3.nvda-addon",
	"tod-dev" => "https://files.derekriemer.com/tipOfTheDay-dev.nvda-addon",
	"tod" => "https://files.derekriemer.com/tipOfTheDay.nvda-addon",
	"tony" => "https://github.com/mltony/nvda-tonys-enhancements/releases/download/v1.10/tonysEnhancements-1.10.nvda-addon",
	"trainingkbdcmd" => "https://github.com/ibrahim-s/trainingNvdaCommands/releases/download/2.4/trainingKeyboardCommands-2.4.nvda-addon",
	"tv" => "teamViewer-2.3.nvda-addon",
	"tv-dev" => "teamViewer-3.0-dev.nvda-addon",
	"txtinfo" => "https://github.com/cartertemm/text_information/releases/download/v1.1/textInformation-1.1.nvda-addon",
	"tz" => "https://github.com/munawarb/NVDA-Time-Zoner/releases/download/v1.04/timezone-1.04.nvda-addon",
	"ubi" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.1/unicodeBrailleInput-3.1.nvda-addon",
	"ubi-dev" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.1/unicodeBrailleInput-3.1.nvda-addon",
	"unmute" => "https://github.com/grisov/Unmute/releases/download/latest/unmute-1.5.5.nvda-addon",
	"updchannelselect" => "https://github.com/nvda-es/updateChannel/releases/download/v1.0.3/updateChannel-1.0.3.nvda-addon",
	"VR" => "https://github.com/ruifontes/virtualReview/releases/download/21.06/virtualRevision-21.06.nvda-addon",
	"vlc" => "https://github.com/javidominguez/VLC/releases/download/2.12/VLC-2.12.nvda-addon",
	"vlc-18" => "https://github.com/javidominguez/VLC/releases/download/2.12/VLC-2.12.nvda-addon",
	"vlc-dev" => "https://github.com/javidominguez/VLC/releases/download/2.12/VLC-2.12.nvda-addon",
	"vent" => "Ventrilo-1.0-dev.nvda-addon",
	"w10" => "https://github.com/josephsl/wintenApps/releases/download/21.06.1/wintenApps-21.06.1.nvda-addon",
	"w10-dev" => "https://www.josephsl.net/files/nvdaaddons/getupdate.php?file=w10-dev",
	"wc" => "https://github.com/ruifontes/wordCount/releases/download/21.05/wordCount-21.05.nvda-addon",
	"wetp" => "https://www.nvda.it/files/plugin/weather_plus8.1.nvda-addon",
	"winmag" => "https://github.com/CyrilleB79/winMag/releases/download/V1.0/winMag-1.0.nvda-addon",
	"winmag-dev" => "https://github.com/CyrilleB79/winMag/releases/download/V1.0/winMag-1.0.nvda-addon",
	"winwizard" => "https://github.com/lukaszgo1/winWizard/releases/download/V5.0.3/winWizard-5.0.3.nvda-addon",
	"wordnav" => "https://github.com/mltony/nvda-word-nav/releases/download/v1.4/wordNav-1.4.nvda-addon",
	"zoom" => "zoomEnhancements-1.0.nvda-addon",
);

If (isset($_GET['file'])) {
	$file = $_GET['file'];
	$fullname = $addons[$file];

	if ($fullname != "") {
		Header('Location:'.$fullname);
	} else {
		header("HTTP/1.0 404 Not Found");
		print "<h1>File not found</h1>";
		print "<p>The file you requested could not be found on this server.</p>";
		print "<p>Please check that the link that brought you here is correct and try again.</p>";
		print "<p>Thanks</p>";
	}
} else If (isset($_GET['addonslist'])) {
	echo json_encode($addons);
} else {
	print "<h1>Error:</h1>";
	print "<p>Please check that the link that brought you here is correct and try again.</p>";
	print "<p>If you continue to see this message report this error to the nvda addon list.</p>";
	print "<p>Thanks</p>";
}
?>
