<?php
$addons = array(
	"access8math" => "https://github.com/tsengwoody/Access8Math/releases/download/v2.3/Access8Math-2.3.nvda-addon",
	"addonshelp" => "https://github.com/ruifontes/addonsHelp/releases/download/2.1.0/addonsHelp-2.1.nvda-addon",
	"ath" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"ath-dev" => "https://github.com/mush42/Audio-Themes-NVDA-Add-on/releases/download/v5.1/AudioThemes3D-5.1.nvda-addon",
	"audiochart" => "audioChart-1.2.nvda-addon",
	"bc" => "bitChe-2.8.nvda-addon",
	"bc-dev" => "bitChe-2.8.nvda-addon",
	"beepkeyboard" => "beepKeyboard-1.3.nvda-addon",
	"bgt" => "https://github.com/sykesman/NVDA-BGT/releases/download/1.0-dev/bgt_lullaby-1.0-dev.nvda-addon",
	"brlext" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest",
	"brlext-dev" => "https://andreabc.net/projects/NVDA_addons/BrailleExtender/latest?channel=dev",
	"browsernav" => "browsernav-1.9.nvda-addon",
	"btaudio" => "bluetoothaudio-1.1.nvda-addon",
	"cac" => "https://github.com/hkatic/clock/releases/download/v19.12/clock-19.12.nvda-addon",
	"cac-dev" => "http://cyber25.free.fr/nvda-addons/clock-19.12-dev.nvda-addon",
	"cae" => "https://github.com/javidominguez/Calibre/releases/download/2.0/calibre-2.0.nvda-addon",
	"cae-dev" => "https://github.com/javidominguez/Calibre/releases/download/2.0/calibre-2.0.nvda-addon",
	"chari" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.3/charInfo-1.3.nvda-addon",
	"chari-dev" => "https://github.com/CyrilleB79/charInfo/releases/download/V1.3/charInfo-1.3.nvda-addon",
	"clsel" => "https://github.com/tspivey/classicSelection/releases/download/v1.1/classicSelection-1.1.nvda-addon",
	"ccd" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/11.0/clipContentsDesigner-11.0.nvda-addon",
	"ccd-dev" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/11.2-dev/clipContentsDesigner-11.2-dev.nvda-addon",
	"ccd-o" => "https://github.com/nvdaes/clipContentsDesigner/releases/download/7.2/clipContentsDesigner-7.2.nvda-addon",
	"ckbl" => "https://github.com/abdel792/sayCurrentKeyboardLanguage/releases/download/v19.12/sayCurrentKeyboardLanguage-19.12.nvda-addon",
	"ckbl-dev" => "http://cyber25.free.fr/nvda-addons/sayCurrentKeyboardLanguage-19.12-dev.nvda-addon",
	"cr" => "columnsReview-3.0-20191212-dev.nvda-addon",
	"cr-dev" => "columnsReview-3.0-20191212-dev.nvda-addon",
	"crh-dev" => "https://files.derekriemer.com/crashHero-dev.nvda-addon",
	"cs" => "clipspeak-1.1.nvda-addon",
	"cont" => "https://github.com/derekriemer/consoleTimer/releases/download/v1.0/consoleTimer-1.0.nvda-addon",
	"cua" => "https://github.com/josephsl/controlUsageAssistant/releases/download/20.01/controlUsageAssistant-20.03.nvda-addon",
	"cua-2019" => "https://github.com/josephsl/controlUsageAssistant/releases/download/19.11/controlUsageAssistant-19.11.nvda-addon",
	"cua-dev" => "https://github.com/josephsl/controlUsageAssistant/releases/download/20.01/controlUsageAssistant-20.03.nvda-addon",
	"debughelper" => "https://github.com/XLTechie/debugHelper/releases/download/v1.0.3/debugHelper-1.0.3.nvda-addon",
	"devtoolkit" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/2020.2/developerToolkit-2020.2.nvda-addon",
	"devtoolkit-dev" => "https://github.com/ajborka/nvda_developer_toolkit/releases/download/2020.2/developerToolkit-2020.2.nvda-addon",
	"dw" => "https://github.com/abdel792/dayOfTheWeek/releases/download/v19.12/dayOfTheWeek-19.12.nvda-addon",
	"dw-dev" => "http://cyber25.free.fr/nvda-addons/dayOfTheWeek-19.12-dev.nvda-addon",
	"dx" => "https://github.com/Nardol/dropbox/releases/download/v4.4/dropbox-4.4.nvda-addon",
	"dx-dev" => "https://github.com/Nardol/dropbox/releases/download/v4.4/dropbox-4.4.nvda-addon",
	"earia" => "https://github.com/jmdaweb/enhancedAria/releases/download/v2.8/enhancedAria-2.8.nvda-addon",
	"em" => "https://github.com/nvdaes/eMule/releases/download/4.0/eMule-4.0.nvda-addon",
	"em-dev" => "https://github.com/nvdaes/eMule/releases/download/4.1-dev/eMule-4.1-dev.nvda-addon",
	"emo" => "https://github.com/nvdaes/emoticons/releases/download/12.0/emoticons-12.0.nvda-addon",
	"emo-dev" => "https://github.com/nvdaes/emoticons/releases/download/12.1-dev/emoticons-12.1-dev.nvda-addon",
	"emo-o" => "https://github.com/nvdaes/emoticons/releases/download/6.5/emoticons-6.5.nvda-addon",
	"etn" => "easyTableNavigator-2.0.nvda-addon",
	"etn-2019" => "easyTableNavigator-1.6.nvda-addon",
	"etn-dev" => "easyTableNavigator-2.0.nvda-addon",
	"ets" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/20.02/enhancedTouchGestures-20.03.nvda-addon",
	"ets-2019" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/19.09/enhancedTouchGestures-19.11.nvda-addon",
	"ets-dev" => "https://github.com/josephsl/enhancedTouchGestures/releases/download/20.02/enhancedTouchGestures-20.03.nvda-addon",
	"ew" => "extendedWinamp-1.2.nvda-addon",
	"fh" => "https://github.com/nvdajp/focusHighlight/releases/download/6.3/focusHighlight-6.3.nvda-addon",
	"fh-dev" => "https://github.com/nvdajp/focusHighlight/releases/download/6.2/focusHighlight-6.2.nvda-addon",
	"gc" => "goldenCursor-4.0.nvda-addon",
	"gc-2019" => "goldenCursor-3.8.nvda-addon",
	"gc-dev" => "goldenCursor-4.0.nvda-addon",
	"gl" => "https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/guideLines",
	"gwv" => "https://github.com/josephsl/goldWave/releases/download/20.01/goldwave-20.03.nvda-addon",
	"gwv-2019" => "https://github.com/josephsl/goldWave/releases/download/19.11/goldwave-19.11.nvda-addon",
	"gwv-dev" => "https://github.com/josephsl/goldWave/releases/download/20.01/goldwave-20.03.nvda-addon",
	"imgdesc" => "https://storage.googleapis.com/www.screenreader.ai/addons/ImageDescriber-1.2.1.nvda-addon",
	"it" => "instantTranslate-4.4.1.nvda-addon",
	"it-dev" => "instantTranslate-4.4.1.nvda-addon",
	"indentnav" => "IndentNav-1.10.nvda-addon",
	"inputlock" => "https://github.com/jmdaweb/inputLock/releases/download/v1.8/inputLock-1.8.nvda-addon",
	"lambda" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"lambda-dev" => "https://github.com/lambda-nvda/lambdaNvda/releases/download/1.3.0/lambda-1.3.0.nvda-addon",
	"mp3dc" => "https://github.com/abdel792/mp3DirectCut/releases/download/v19.12/mp3DirectCut-19.12.nvda-addon",
	"mp3dc-dev" => "http://cyber25.free.fr/nvda-addons/mp3DirectCut-19.12-dev.nvda-addon",
	"mirc" => "mirc-1.6.nvda-addon",
	"moz" => "https://github.com/javidominguez/MozillaScripts/releases/download/1.10/Mozilla-1.10.nvda-addon",
	"mush" => "mushClient-1.3.nvda-addon",
	"nb" => "noBeepsSpeechMode-2.5.nvda-addon",
	"NotepadPlusPlus" => "https://files.derekriemer.com/NotepadPlusPlus-2019.09.0.nvda-addon",
	"nvda3208" => "https://github.com/josephsl/addonUpdater/releases/download/19.11/addonUpdater-20.02.2.nvda-addon",
	"nvda7857" => "screenCurtain-20191130.nvda-addon",
	"nvdaremote" => "https://nvdaremote.com/remote-2.3.nvda-addon",
	"objLoc" => "https://github.com/josephsl/objLocationTones/releases/download/20.01/objLocTones-20.01.nvda-addon",
	"objLoc-2019" => "https://github.com/josephsl/objLocationTones/releases/download/19.05/objLocTones-19.05.2.nvda-addon",
	"objPad" => "https://github.com/josephsl/objPad/releases/download/20.01/objPad-20.01.nvda-addon",
	"objPad-2019" => "https://github.com/josephsl/objPad/releases/download/19.05/objPad-19.05.2.nvda-addon",
	"objPad-dev" => "https://github.com/josephsl/objPad/releases/download/20.01/objPad-20.01.nvda-addon",
	"ocr" => "https://www.nvaccess.org/files/nvda-addons/ocr_0.20120529.01.nvda-addon",
	"oid-dev" => "https://github.com/larry801/online_ocr/releases/download/0.17-dev/onlineOCR-0.17-dev.nvda-addon",
	"outlookextended" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.5/outlookExtended-1.5.nvda-addon",
	"outlookextended-dev" => "https://github.com/CyrilleB79/outlookExtended/releases/download/V1.5/outlookExtended-1.5.nvda-addon",
	"pckbbrl" => "https://github.com/nvdaes/pcKbBrl/releases/download/2019.1/pcKbBrl-2019.1.nvda-addon",
	"pckbbrl-dev" => "https://github.com/nvdaes/pcKbBrl/releases/download/2019.1.1-dev/pcKbBrl-2019.1.1-dev.nvda-addon",
	"pckbbrl-o" => "https://www.nvaccess.org/files/nvda-addons/pcKbBrl-2014.1.nvda-addon",
	"perChk" => "https://github.com/lukaszgo1/percentageChecker/releases/download/v1.3-dev/percentageChecker-1.3-dev.nvda-addon",
	"pm" => "https://github.com/nvdaes/placeMarkers/releases/download/14.0/placeMarkers-14.0.nvda-addon",
	"pm-dev" => "https://github.com/nvdaes/placeMarkers/releases/download/14.3-dev/placeMarkers-14.3-dev.nvda-addon",
	"pm-o" => "https://github.com/nvdaes/placeMarkers/releases/download/10.2/placeMarkers-10.2.nvda-addon",
	"qb-dev" => "https://www.nvaccess.org/files/nvda-addons/quickBooks2014-2014.4.7.nvda-addon",
	"rccp" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.2/reviewCursorCopier-1.2.nvda-addon",
	"rccp-dev" => "https://github.com/tuukkao/nvda-reviewCursorCopier/releases/download/1.2/reviewCursorCopier-1.2.nvda-addon",
	"rf" => "https://github.com/nvdaes/readFeeds/releases/download/9.0/readFeeds-9.0.nvda-addon",
	"rf-dev" => "https://github.com/nvdaes/readFeeds/releases/download/9.0-dev/readFeeds-9.0-dev.nvda-addon",
	"rf-o" => "https://github.com/nvdaes/readFeeds/releases/download/4.5/readFeeds-4.5.nvda-addon",
	"rm" => "https://github.com/josephsl/resourceMonitor/releases/download/20.01/resourceMonitor-20.03.nvda-addon",
	"rm-2019" => "https://github.com/josephsl/resourceMonitor/releases/download/19.11/resourceMonitor-19.11.1.nvda-addon",
	"rm-dev" => "https://github.com/josephsl/resourceMonitor/releases/download/20.01/resourceMonitor-20.03.nvda-addon",
	"rp" => "https://github.com/nvdaes/reportPasswords/releases/download/1.0/reportPasswords-1.0.nvda-addon",
	"rp-dev" => "https://github.com/nvdaes/reportPasswords/releases/download/1.6-dev/reportPasswords-1.6-dev.nvda-addon",
	"rs-dev" => "rapidSettings-2.0-dev.nvda-addon",
	"rsy" => "https://github.com/nvdaes/reportSymbols/releases/download/5.0/reportSymbols-5.0.nvda-addon",
	"rsy-dev" => "https://github.com/nvdaes/reportSymbols/releases/download/5.1-dev/reportSymbols-5.1-dev.nvda-addon",
	"rsy-o" => "https://github.com/nvdaes/reportSymbols/releases/download/3.6/reportSymbols-3.6.nvda-addon",
	"sentencenav" => "SentenceNav-2.7.nvda-addon",
	"spie" => "https://www.nvaccess.org/files/nvda-addons/speechPlayerInEspeak-0.4.nvda-addon",
	"spl" => "https://github.com/josephsl/stationPlaylist/releases/download/20.03/stationPlaylist-20.03.nvda-addon",
	"spl-2019" => "https://github.com/josephsl/stationPlaylist/releases/download/19.11.1/stationPlaylist-19.11.2.nvda-addon",
	"spl-lts18" => "https://github.com/josephsl/stationPlaylist/releases/download/19.11.1/stationPlaylist-18.09.13-lts.nvda-addon",
	"spl-dev" => "https://www.josephsl.net/files/nvdaaddons/getupdate.php?file=spl-dev",
	"sps" => "https://github.com/jscholes/nvda-speech-history/releases/download/v2019.03.30/speechHistory.nvda-addon",
	"st" => "systrayList-4.0.nvda-addon",
	"st-2019" => "systrayList-3.7.nvda-addon",
	"st-dev" => "systrayList-4.0.nvda-addon",
	"sws" => "https://github.com/tspivey/switchSynth/releases/download/v1.03/switchSynth-1.03.nvda-addon",
	"spp" => "https://github.com/tspivey/speakPasswords/releases/download/v1.01/speakPasswords-1.01.nvda-addon",
	"synthrings" => "synthRingSettingsSelector-0.6.nvda-addon",
	"tbx" => "toolbarsExplorer-1.4.nvda-addon",
	"tbx-dev" => "toolbarsExplorer-1.4-20190825-dev.nvda-addon",
	"textnav" => "textnav-1.4.nvda-addon",
	"tmast" => "https://github.com/nvdaaddons/toneMaster/releases/download/v1.3/toneMaster-1.3.nvda-addon",
	"tod-dev" => "https://files.derekriemer.com/tipOfTheDay-dev.nvda-addon",
	"tod" => "https://files.derekriemer.com/tipOfTheDay.nvda-addon",
	"trainingkbdcmd" => "https://github.com/ibrahim-s/trainingNvdaCommands/releases/download/v1.1/trainingKeyboardCommands-1.1-dev.nvda-addon",
	"tv" => "teamViewer-2.3.nvda-addon",
	"tv-dev" => "teamViewer-3.0-dev.nvda-addon",
	"txtinfo" => "https://github.com/cartertemm/text_information/releases/download/1.0/textInformation-1.0.nvda-addon",
	"ubi" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.1/unicodeBrailleInput-3.1.nvda-addon",
	"ubi-dev" => "https://github.com/leonardder/unicodebrailleinput/releases/download/3.1/unicodeBrailleInput-3.1.nvda-addon",
	"VR" => "virtualRevision-3.0.nvda-addon",
	"VR-2019" => "virtualRevision-2.8.nvda-addon",
	"vlc" => "https://github.com/javidominguez/VLC/releases/download/2.10/VLC-2.10.nvda-addon",
	"vlc-18" => "https://github.com/javidominguez/VLC/releases/download/2.10/VLC-2.10.nvda-addon",
	"vlc-dev" => "https://github.com/javidominguez/VLC/releases/download/2.10/VLC-2.10.nvda-addon",
	"vent" => "Ventrilo-1.0-dev.nvda-addon",
	"w10" => "https://github.com/josephsl/wintenApps/releases/download/20.03/wintenApps-20.03.nvda-addon",
	"w10-2019" => "https://github.com/josephsl/wintenApps/releases/download/19.11/wintenApps-19.11.5.nvda-addon",
	"w10-dev" => "https://www.josephsl.net/files/nvdaaddons/getupdate.php?file=w10-dev",
	"wc" => "https://github.com/ruifontes/wordCount/releases/download/1.4/wordCount-1.4.nvda-addon",
	"wetp" => "http://www.nvda.it/files/plugin/weather_plus7.4.nvda-addon",
	"winmag" => "https://github.com/CyrilleB79/winMag/releases/download/V1.0-dev-20200225/winMag-1.0-dev-20200225.nvda-addon",
	"winmag-dev" => "https://github.com/CyrilleB79/winMag/releases/download/V1.0-dev-20200225/winMag-1.0-dev-20200225.nvda-addon",
);

If (isset($_GET['file'])) {
	$file = $_GET['file'];
	$fullname = $addons[$file];

	if ($fullname != "") {
		Header('Location:'.$fullname);
	} else {
		header("HTTP/1.0 404 Not Found");
		print "<h1>File not found</h1>";
		print "<p>The file you requested could not be found on this server.</p>";
		print "<p>Please check that the link that brought you here is correct and try again.</p>";
		print "<p>Thanks</p>";
	}
} else If (isset($_GET['addonslist'])) {
	echo json_encode($addons);
} else {
	print "<h1>Error:</h1>";
	print "<p>Please check that the link that brought you here is correct and try again.</p>";
	print "<p>If you continue to see this message report this error to the nvda addon list.</p>";
	print "<p>Thanks</p>";
}
?>
